defaults:
  #languages
  -
    scope:
      path: ""
    values:
      lang: "en"
      layout: default
  -
    scope:
      path: "en"
    values:
      lang: "en"
  -
    scope:
      path: "nl"
    values:
      lang: "nl"